# BASED ON LANDMARK 1D AXIAL HYBRID BENCHMARK:

[Mesh]
nx = 100
ny = 40
ng = 2
xlim = (0, 0.05)
ylim = (0.035, 0.05)

[Time]
time_steps = 3000
method = RK1
t0 = 0
t_finish = 1e-3
cfl = 0.2
dt = 1e-8

[Electrons]
system = quasineutral
ics = static
density = 9.10938e-7
pressure = 1.6021766
T_e = 300000
gammas = [1.4]
mW = [28]

[Ions]
system = pic
ics = random
n_ppc = 10
n_i = 0

[Neutrals]
system = pic
v_n = 150
flux_n = 5.7257e21
n_n = 0
; n_n_anode = 3.2e19
; n_n_downstream = 1.6e19 

[Method]
flux = rusanov
bcs_lo = (neumann, neumann)
bcs_hi = (neumann, neumann)
collision_type = rate_coeffs

[Fields]
V_anode = 300
V_cathode = 0
B_ics = guillaume
B_max = 0.015

[Parameters]
propellant = xe
charge = 1.602e-19
e_mass = 9.10938e-31
i_mass = 2.18e-25
n_mass = 2.18e-25

[Output]
#output_freq = 1.843657e-8
#output_dir = ''
output_freq = 1
make_movie = true
2d_data = n_e, u_e, eps_e, By, n_n, n_i, n, i, Ex, phi
# n_e, p_e, u_e, w_e, rho_q, phi, Ex, By, rho_n, i, rho_i, n
