[Mesh]
nx = 100
ny = 100
ng = 2
xlim = (0, 10)
ylim = (0, 10)

[Time]
time_steps = 500
method = RK1
t0 = 0
t_finish = 10
cfl = 0.9

[Fluid]
fluid_ics = tame_static
system = euler2d
gammas = [1.4]
mW = [28]

[Method]
flux = hllc
bcs_lo = (neumann, neumann)
bcs_hi = (neumann, neumann)

[Particle]
; particle_ics = random
; n_particles_per_cell = 100
; flow_type = multispecies
#seeding_per_timestep = 0
#bounce_back_multiplier = 1.0
#max_number_of_bounces = 3

[Fields]
E_ics = pass
B_ics = guillaume

[Output]
output_freq = 1
#output_dir = ''
make_movie = true

