# BASED ON LANDMARK 1D AXIAL HYBRID BENCHMARK:

[Mesh]
nx = 100
ny = 40
ng = 2
# get real dimensions to work here + in plasma_refs...
xlim = (0, 0.05)
ylim = (0, 0.015)

[Time]
time_steps = 3000
method = RK1
t0 = 0
t_finish = 10
cfl = 0.2
dt = 1e-12

[Fluid]
; fluid_ics = tame_static
density = 9.10938e-13
pressure = 1.6021766
system = euler2d
gammas = [1.4]
mW = [28]

[Particle]
# General
particle_ics = random
n_ppc = 1
flow_type = multispecies

# Neutrals
n_mass = 2.18e-25 # kg
; n_n_anode = 3.2e19
; n_n_downstream = 1.6e19 
v_n = 150
n_flow_rate = 5e-6

# Misc
#seeding_per_timestep = 0
#bounce_back_multiplier = 1.0
#max_number_of_bounces = 3


[Method]
flux = rusanov_vectorized
bcs_lo = (neumann, neumann)
bcs_hi = (tame_inflow, neumann)


[Fields]
V_anode = 300
V_cathode = 0
B_ics = guillaume
B_max = 0.015

[Parameters]
charge = 1.602e-19
e_mass = 9.10938e-31
i_mass = 2.18e-25
n_mass = 2.18e-25

[Output]
output_freq = 1
#output_dir = ''
make_movie = true
2d_data = rho_e, p_e, u_e, mw_e, rho_q, phi, Ex, n, rho_n, i, rho_i, sigma
